on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 2 * *"

name: make

jobs:
  make:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "pkgdown"))
          remotes::install_cran("devtools")
          remotes::install_cran("seqinr")
          remotes::install_cran("data.table")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_github("richelbilderbeek/mhcnuggetsr")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("jtextor/epitope-prediction")
          remotes::install_github("richelbilderbeek/pureseqtmr")
        shell: Rscript {0}

      - name: Install PureseqTM
        run: pureseqtmr::install_pureseqtm()
        shell: Rscript {0}

      - name: Make
        run: make

